//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public string PedidoCodigo { get; set; }
        public string PedidoDescripcion { get; set; }
        public Nullable<decimal> ValorPedido { get; set; }
        public System.DateTime PedidoFechaEmision { get; set; }
        public System.DateTime PedidoFechaRecepcion { get; set; }
        public string PedidoEstado { get; set; }
        public string ProveedorCodigo { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
