//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ProductoCodigo { get; set; }
        public String ProductoNombre { get; set; }
        public String ProductoDescripcion { get; set; }
        public Double ProductoPrecioCompra { get; set; }
        public Double ProductoPrecioVenta { get; set; }
        public String ProductoUnidadesVendidas { get; set; }
        public String ProductoMarca { get; set; }
        public String ProductoStock { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public int CategoriaCodigo { get; set; }
        public int PedidoCodigo { get; set; }
        public int GerenteCodigo { get; set; }
    
        public virtual Gerente Gerente { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
